server:
  port: 8100
spring:
  application:
    name: microservice-provider
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    enabled: true
    compression:
      enabled: true
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:7100/eureka/
      #以下是注册到eureka集群，建议全部节点都写
      #defaultZone: http://peer1:7100/eureka/,http://peer2:7200/eureka/,http://peer3:7300/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}