server:
  port: 9100
spring:
  application:
    mainclass: com.zhht.cloud.ConsumerFeignApplication
    name: microservice-consumer-feign-kafka
  kafka:
    producer:
      client-id: ${spring.application.name}
    bootstrap-servers:
    - 10.110.59.23:9092
  sleuth:
    enabled: true
    sampler:
      percentage: 1
#  profiles:
#    active: ${environment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:7100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    
logging:
  appender: console
  path: D:/data/testlogs/
  level:
    com.netflix: warn
  pattern:
   level: info
    