spring:
  application:
    name: microservice-getway-zuul
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
server:
  port: 7070
  
security:
  user:
    name: admin
    password: admin123
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    
zuul:
  ignoredServices: '*' #忽悠所有微服务代理，忽略一个可以指定，可以是用逗号分隔多个
  routes:
    microservice-provider-user: #微服务名
      path: /myusers/**
      strip-prefix: true 
    microservice-provider-v2: #微服务名
#禁用具体的filter
#zuul.SendResponseFilter.post.disable: true
      path: /mymoves/**
      strip-prefix: true 
    legacy:
      path: /** #前面路由规则匹配失败会走legacy规则，必须使用yml格式
  prefix: /2.0 #需要写斜杠‘/’

  
  
ribbon.restclient.enabled: true #zuul使用的默认HTTP客户端现在由Apache HTTP Client支持,推荐使用restclient   

logging:
  level:
    com.netflix: debug