server:
  port: 7100

security:
  user:
    name: admin
    password: admin123
spring:
  application:
    name: microservice-eureka
  profiles:
    active: test
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:7100/eureka/
      
eureka.datacenter: cloud

eureka.environment: preproduct